source "https://rubygems.org"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.0.2"
# Use PostgreSQL as the database for Active Record
gem "pg"
# Use the Puma web server
gem "puma", ">= 5.0"

# API関連
gem "rack-cors"
gem "active_model_serializers"

# パフォーマンス向上
gem "bootsnap", require: false
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

# デプロイ
gem "kamal", require: false
gem "thruster", require: false

# Windows対応
gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end
